Repository DefangLabs/defang, pull requests merged in 2024-10, with the labels that each got.

#729 Fix for AWS BYOC empty WorkingDirectory
  src/pkg/clouds/aws/ecs/cfn/template.go
Labels: byoc, bug

#735 Bump Go to 1.22
  flake.nix
  src/go.mod
Labels: ai, go

#727 Fix DO follow log flow
  src/pkg/cli/client/byoc/do/byoc.go
Labels: digitalocean

#745 Extend CD grace period to 10min
  src/pkg/clouds/do/appPlatform/setup.go
  src/pkg/clouds/do/appPlatform/setup_test.go
Labels: digitalocean

#755 Print real error, not missing tail perm
  src/cmd/cli/command/compose.go
Labels: bug

#520 Add preview mode
  src/cmd/cli/command/commands.go
  src/cmd/cli/command/compose.go
  src/pkg/cli/cert_test.go
  src/pkg/cli/client/byoc/aws/byoc.go
  src/pkg/cli/client/byoc/do/byoc.go
  src/pkg/cli/client/client.go
  src/pkg/cli/client/playground.go
  src/pkg/cli/compose/context.go
  src/pkg/cli/compose/convert.go
  src/pkg/cli/compose/convert_test.go
  src/pkg/cli/compose/validation_test.go
  src/pkg/cli/composeUp.go
  src/pkg/cli/composeUp_test.go
  src/pkg/cli/getServices.go
Labels: byoc
